// Writes `src/parser/unicode_generated.rs`, the table the parser looks
// characters up in, which is every character unicode gives a punctuation
// (`P*`) or symbol (`S*`) category. Run it with
// `deno run -A scripts/generate_unicode_punctuation.ts` to update the table
// for a newer version of unicode.

const isPunctuation = /[\p{P}\p{S}]/u;

const ranges: [number, number][] = [];
let start = -1;
// the table only covers what's beyond ascii, which is checked directly
for (let code = 0x80; code <= 0x10ffff; code++) {
  // surrogates aren't characters of their own
  const isSurrogate = code >= 0xd800 && code <= 0xdfff;
  if (!isSurrogate && isPunctuation.test(String.fromCodePoint(code))) {
    if (start < 0) {
      start = code;
    }
  } else if (start >= 0) {
    ranges.push([start, code - 1]);
    start = -1;
  }
}
if (start >= 0) {
  ranges.push([start, 0x10ffff]);
}

const hex = (code: number) => `0x${code.toString(16).padStart(4, "0")}`;
const rows = ranges
  .map(([start, end]) => `  (${hex(start)}, ${hex(end)}),`)
  .join("\n");

const text = `// @generated by scripts/generate_unicode_punctuation.ts -- do not edit by hand

/// Every character beyond ascii that unicode gives a punctuation (\`P*\`) or
/// symbol (\`S*\`) category, as the inclusive ranges the codes fall in, sorted
/// and never touching so that a code can be looked up by binary search.
#[rustfmt::skip]
pub(super) static PUNCTUATION_RANGES: [(u32, u32); ${ranges.length}] = [
${rows}
];
`;

await Deno.writeTextFile(new URL("../src/parser/unicode_generated.rs", import.meta.url), text);
